language: node_js
node_js:
  - "node"
services:
  - docker
before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
after_success:
  - docker build -t internetofdrums/internet-drum-pattern-queue-client .
  - docker push internetofdrums/internet-drum-pattern-queue-client
